"""Catalogue statique de la Mishna (source : API Sefaria).

Les 63 traités, leur ordre canonique (les six sedarim) et la structure de
chaque traité (nombre de mishnayot par chapitre) proviennent de l'API
Sefaria (``api/counts/{traité}``), relevés une fois pour toutes afin que
l'application n'ait **pas besoin du réseau** pour remplir les listes
déroulantes de l'onglet « Livre ».

La traduction française utilisée est « Le Talmud de Jérusalem, traduit par
Moise Schwab, 1878-1890 » (domaine public), qui ne couvre que 38 traités
(``SCHWAB_TRACTATES``) ; pour les autres, seul le texte hébreu (« Torat
Emet 357 », domaine public) est affiché.
"""

# Sedarim dans l'ordre canonique, puis traités dans l'ordre canonique.
SEDARIM = [
    ("Seder Zeraim", [
        ("Mishnah Berakhot", "Bérakhot (Bénédictions)"),
        ("Mishnah Peah", "Pea (Coin du champ)"),
        ("Mishnah Demai", "Demaï (Dîme douteuse)"),
        ("Mishnah Kilayim", "Kilayim (Mélanges)"),
        ("Mishnah Sheviit", "Sheviit (Année sabbatique)"),
        ("Mishnah Terumot", "Terumot (Prélèvements)"),
        ("Mishnah Maasrot", "Maassérot (Dîmes)"),
        ("Mishnah Maaser Sheni", "Maasser Sheni (Seconde dîme)"),
        ("Mishnah Challah", "Halla (Pâte prélevée)"),
        ("Mishnah Orlah", "Orla (Incirconcision des arbres)"),
        ("Mishnah Bikkurim", "Bikkourim (Prémices)"),
    ]),
    ("Seder Moed", [
        ("Mishnah Shabbat", "Shabbat (Sabbat)"),
        ("Mishnah Eruvin", "Erouvin (Limites de Shabbat)"),
        ("Mishnah Pesachim", "Pessa'him (Pâque)"),
        ("Mishnah Shekalim", "Shekalim (Le demi-sicle)"),
        ("Mishnah Yoma", "Yoma (Jour du pardon)"),
        ("Mishnah Sukkah", "Soukka (Cabane)"),
        ("Mishnah Beitzah", "Beitsa (Œuf de fête)"),
        ("Mishnah Rosh Hashanah", "Roch Hachana (Nouvel an)"),
        ("Mishnah Taanit", "Taanit (Jeûnes)"),
        ("Mishnah Megillah", "Meguila (Rouleau d'Esther)"),
        ("Mishnah Moed Katan", "Moed Katan (Fête mineure)"),
        ("Mishnah Chagigah", "Haguiga (Pèlerinage)"),
    ]),
    ("Seder Nashim", [
        ("Mishnah Yevamot", "Yevamot (Lévirat)"),
        ("Mishnah Ketubot", "Ketouvot (Contrats de mariage)"),
        ("Mishnah Nedarim", "Nédarim (Vœux)"),
        ("Mishnah Nazir", "Nazir (Nazaréen)"),
        ("Mishnah Sotah", "Sota (Femme suspecte)"),
        ("Mishnah Gittin", "Guittin (Actes de divorce)"),
        ("Mishnah Kiddushin", "Kiddouchin (Fiançailles)"),
    ]),
    ("Seder Nezikin", [
        ("Mishnah Bava Kamma", "Bava Qamma (Première porte)"),
        ("Mishnah Bava Metzia", "Bava Metsia (Porte moyenne)"),
        ("Mishnah Bava Batra", "Bava Batra (Dernière porte)"),
        ("Mishnah Sanhedrin", "Sanhédrin (Tribunal)"),
        ("Mishnah Makkot", "Makkot (Coups)"),
        ("Mishnah Shevuot", "Shevouot (Serments)"),
        ("Mishnah Eduyot", "Edouyot (Témoignages)"),
        ("Mishnah Avodah Zarah", "Avoda Zara (Idolâtrie)"),
        ("Pirkei Avot", "Pirké Avot (Maximes des Pères)"),
        ("Mishnah Horayot", "Horayot (Instructions)"),
    ]),
    ("Seder Kodashim", [
        ("Mishnah Zevachim", "Zevahim (Sacrifices)"),
        ("Mishnah Menachot", "Menahot (Obligations)"),
        ("Mishnah Chullin", "Houllin (Bêtes profanes)"),
        ("Mishnah Bekhorot", "Bekhorot (Premiers-nés)"),
        ("Mishnah Arakhin", "Arakhin (Évaluations)"),
        ("Mishnah Temurah", "Temoura (Substitution)"),
        ("Mishnah Keritot", "Keritot (Extirpations)"),
        ("Mishnah Meilah", "Meila (Sacro-lèse)"),
        ("Mishnah Tamid", "Tamid (Offrande permanente)"),
        ("Mishnah Middot", "Middot (Mesures du Temple)"),
        ("Mishnah Kinnim", "Kinnim (Nids d'oiseaux)"),
    ]),
    ("Seder Tahorot", [
        ("Mishnah Kelim", "Kelim (Vaisseaux)"),
        ("Mishnah Oholot", "Oholot (Tentes)"),
        ("Mishnah Negaim", "Nega'im (Lèpres)"),
        ("Mishnah Parah", "Para (Vache rousse)"),
        ("Mishnah Tahorot", "Tahorot (Purités)"),
        ("Mishnah Mikvaot", "Mikvaot (Bains rituels)"),
        ("Mishnah Niddah", "Nidda (Menstruations)"),
        ("Mishnah Makhshirin", "Makhchirin (Préparations)"),
        ("Mishnah Zavim", "Zavim (Écoulements)"),
        ("Mishnah Tevul Yom", "Tevoul Yom (Immergé du jour)"),
        ("Mishnah Yadayim", "Yadayim (Mains)"),
        ("Mishnah Oktzin", "Otsin (Poignées)"),
    ]),
]

# Nombre de mishnayot par chapitre, pour chaque traité.
# Clé : titre Sefaria ; valeur : liste où l'index 0 = chapitre 1.
STRUCTURE = {
    "Mishnah Berakhot": [5, 8, 6, 7, 5, 8, 5, 8, 5],
    "Mishnah Peah": [6, 8, 8, 11, 8, 11, 8, 9],
    "Mishnah Demai": [4, 5, 6, 7, 11, 12, 8],
    "Mishnah Kilayim": [9, 11, 7, 9, 8, 9, 8, 6, 10],
    "Mishnah Sheviit": [8, 10, 10, 10, 9, 6, 7, 11, 9, 9],
    "Mishnah Terumot": [10, 6, 9, 13, 9, 6, 7, 12, 7, 12, 10],
    "Mishnah Maasrot": [8, 8, 10, 6, 8],
    "Mishnah Maaser Sheni": [7, 10, 13, 12, 15],
    "Mishnah Challah": [9, 8, 10, 11],
    "Mishnah Orlah": [9, 17, 9],
    "Mishnah Bikkurim": [11, 11, 12, 5],
    "Mishnah Shabbat": [11, 7, 6, 2, 4, 10, 4, 7, 7, 6, 6, 6, 7, 4, 3, 8, 8, 3, 6, 5, 3, 6, 5, 5],
    "Mishnah Eruvin": [10, 6, 9, 11, 9, 10, 11, 11, 4, 15],
    "Mishnah Pesachim": [7, 8, 8, 9, 10, 6, 13, 8, 11, 9],
    "Mishnah Shekalim": [7, 5, 4, 9, 6, 6, 7, 8],
    "Mishnah Yoma": [8, 7, 11, 6, 7, 8, 5, 9],
    "Mishnah Sukkah": [11, 9, 15, 10, 8],
    "Mishnah Beitzah": [10, 10, 8, 7, 7],
    "Mishnah Rosh Hashanah": [9, 9, 8, 9],
    "Mishnah Taanit": [7, 10, 9, 8],
    "Mishnah Megillah": [11, 6, 6, 10],
    "Mishnah Moed Katan": [10, 5, 9],
    "Mishnah Chagigah": [8, 7, 8],
    "Mishnah Yevamot": [4, 10, 10, 13, 6, 6, 6, 6, 6, 9, 7, 6, 13, 9, 10, 7],
    "Mishnah Ketubot": [10, 10, 9, 12, 9, 7, 10, 8, 9, 6, 6, 4, 11],
    "Mishnah Nedarim": [4, 5, 11, 8, 6, 10, 9, 7, 10, 8, 12],
    "Mishnah Nazir": [7, 10, 7, 7, 7, 11, 4, 2, 5],
    "Mishnah Sotah": [9, 6, 8, 5, 5, 4, 8, 7, 15],
    "Mishnah Gittin": [6, 7, 8, 9, 9, 7, 9, 10, 10],
    "Mishnah Kiddushin": [10, 10, 13, 14],
    "Mishnah Bava Kamma": [4, 6, 11, 9, 7, 6, 7, 7, 12, 10],
    "Mishnah Bava Metzia": [8, 11, 12, 12, 11, 8, 11, 9, 13, 6],
    "Mishnah Bava Batra": [6, 14, 8, 9, 11, 8, 4, 8, 10, 8],
    "Mishnah Sanhedrin": [6, 5, 8, 5, 5, 6, 11, 7, 6, 6, 6],
    "Mishnah Makkot": [10, 8, 16],
    "Mishnah Shevuot": [7, 5, 11, 13, 5, 7, 8, 6],
    "Mishnah Eduyot": [14, 10, 12, 12, 7, 3, 9, 7],
    "Mishnah Avodah Zarah": [9, 7, 10, 12, 12],
    "Pirkei Avot": [18, 16, 18, 22, 23, 11],
    "Mishnah Horayot": [5, 7, 8],
    "Mishnah Zevachim": [4, 5, 6, 6, 8, 7, 6, 12, 7, 8, 8, 6, 8, 10],
    "Mishnah Menachot": [4, 5, 7, 5, 9, 7, 6, 7, 9, 9, 9, 5, 11],
    "Mishnah Chullin": [7, 10, 7, 7, 5, 7, 6, 6, 8, 4, 2, 5],
    "Mishnah Bekhorot": [7, 9, 4, 10, 6, 12, 7, 10, 8],
    "Mishnah Arakhin": [4, 6, 5, 4, 6, 5, 5, 7, 8],
    "Mishnah Temurah": [6, 3, 5, 4, 6, 5, 6],
    "Mishnah Keritot": [7, 6, 10, 3, 8, 9],
    "Mishnah Meilah": [4, 9, 8, 6, 5, 6],
    "Mishnah Tamid": [4, 5, 9, 3, 6, 3, 4],
    "Mishnah Middot": [9, 6, 8, 7, 4],
    "Mishnah Kinnim": [4, 5, 6],
    "Mishnah Kelim": [9, 8, 8, 4, 11, 4, 6, 11, 8, 8, 9, 8, 8, 8, 6, 8, 17, 9, 10, 7, 3, 10, 5, 17, 9, 9, 12, 10, 8, 4],
    "Mishnah Oholot": [8, 7, 7, 3, 7, 7, 6, 6, 16, 7, 9, 8, 6, 7, 10, 5, 5, 10],
    "Mishnah Negaim": [6, 5, 8, 11, 5, 8, 5, 10, 3, 10, 12, 7, 12, 13],
    "Mishnah Parah": [4, 5, 11, 4, 9, 5, 12, 11, 9, 6, 9, 11],
    "Mishnah Tahorot": [9, 8, 8, 13, 9, 10, 9, 9, 9, 8],
    "Mishnah Mikvaot": [8, 10, 4, 5, 6, 11, 7, 5, 7, 8],
    "Mishnah Niddah": [7, 7, 7, 7, 9, 14, 5, 4, 11, 8],
    "Mishnah Makhshirin": [6, 11, 8, 10, 11, 8],
    "Mishnah Zavim": [6, 4, 3, 7, 12],
    "Mishnah Tevul Yom": [5, 8, 6, 7],
    "Mishnah Yadayim": [5, 4, 5, 8],
    "Mishnah Oktzin": [6, 10, 12],
}

# Traités couverts par la traduction française de Schwab (38/63).
SCHWAB_TRACTATES = frozenset({
    "Mishnah Berakhot",
    "Mishnah Peah",
    "Mishnah Demai",
    "Mishnah Kilayim",
    "Mishnah Sheviit",
    "Mishnah Terumot",
    "Mishnah Maasrot",
    "Mishnah Challah",
    "Mishnah Orlah",
    "Mishnah Bikkurim",
    "Mishnah Shabbat",
    "Mishnah Eruvin",
    "Mishnah Pesachim",
    "Mishnah Shekalim",
    "Mishnah Yoma",
    "Mishnah Sukkah",
    "Mishnah Beitzah",
    "Mishnah Rosh Hashanah",
    "Mishnah Taanit",
    "Mishnah Megillah",
    "Mishnah Moed Katan",
    "Mishnah Chagigah",
    "Mishnah Yevamot",
    "Mishnah Ketubot",
    "Mishnah Nedarim",
    "Mishnah Nazir",
    "Mishnah Sotah",
    "Mishnah Gittin",
    "Mishnah Kiddushin",
    "Mishnah Bava Kamma",
    "Mishnah Bava Metzia",
    "Mishnah Bava Batra",
    "Mishnah Sanhedrin",
    "Mishnah Makkot",
    "Mishnah Shevuot",
    "Mishnah Avodah Zarah",
    "Mishnah Horayot",
    "Mishnah Niddah",
})
